"""Create institutional_profiles table

Revision ID: 005a6a095f04
Revises: 20ddeaf862eb
Create Date: 2025-11-13 10:01:12.141780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '005a6a095f04'
down_revision: Union[str, Sequence[str], None] = '20ddeaf862eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('institutional_profiles', sa.Column('firm_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('institutional_profiles', sa.Column('philosophy', sa.Text(), nullable=True))
    op.add_column('institutional_profiles', sa.Column('profile_img', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('institutional_profiles', 'profile',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_column('institutional_profiles', 'state')
    op.drop_column('institutional_profiles', 'phone')
    op.drop_column('institutional_profiles', 'name')
    op.drop_column('institutional_profiles', 'country')
    op.drop_column('institutional_profiles', 'address')
    op.drop_column('institutional_profiles', 'city')
    op.drop_column('institutional_profiles', 'website')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('institutional_profiles', sa.Column('website', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('institutional_profiles', sa.Column('city', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('institutional_profiles', sa.Column('address', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('institutional_profiles', sa.Column('country', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('institutional_profiles', sa.Column('name', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('institutional_profiles', sa.Column('phone', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('institutional_profiles', sa.Column('state', mysql.VARCHAR(length=255), nullable=True))
    op.alter_column('institutional_profiles', 'profile',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_column('institutional_profiles', 'profile_img')
    op.drop_column('institutional_profiles', 'philosophy')
    op.drop_column('institutional_profiles', 'firm_type')
    # ### end Alembic commands ###
