"""update reported financials

Revision ID: 15df50845d07
Revises: 307a6faf8e89
Create Date: 2025-11-14 21:39:27.938129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15df50845d07'
down_revision: Union[str, Sequence[str], None] = '307a6faf8e89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reported_financials', sa.Column('report', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reported_financials', 'report')
    # ### end Alembic commands ###
