"""update sector metrics

Revision ID: 20ddeaf862eb
Revises: 350e20a82687
Create Date: 2025-11-13 06:29:08.470172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '20ddeaf862eb'
down_revision: Union[str, Sequence[str], None] = '350e20a82687'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sector_metrics', sa.Column('metrics', sa.JSON(), nullable=True))
    op.drop_column('sector_metrics', 'dividend_yield')
    op.drop_column('sector_metrics', 'roe')
    op.drop_column('sector_metrics', 'pb_ratio')
    op.drop_column('sector_metrics', 'market_cap')
    op.drop_column('sector_metrics', 'debt_to_equity')
    op.drop_column('sector_metrics', 'roa')
    op.drop_column('sector_metrics', 'pe_ratio')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sector_metrics', sa.Column('pe_ratio', mysql.FLOAT(), nullable=True))
    op.add_column('sector_metrics', sa.Column('roa', mysql.FLOAT(), nullable=True))
    op.add_column('sector_metrics', sa.Column('debt_to_equity', mysql.FLOAT(), nullable=True))
    op.add_column('sector_metrics', sa.Column('market_cap', mysql.FLOAT(), nullable=True))
    op.add_column('sector_metrics', sa.Column('pb_ratio', mysql.FLOAT(), nullable=True))
    op.add_column('sector_metrics', sa.Column('roe', mysql.FLOAT(), nullable=True))
    op.add_column('sector_metrics', sa.Column('dividend_yield', mysql.FLOAT(), nullable=True))
    op.drop_column('sector_metrics', 'metrics')
    # ### end Alembic commands ###
