"""Update price_metrics table to match API response

Revision ID: 285586c4bbdb
Revises: efaf274996bd
Create Date: 2025-11-12 23:52:04.290377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '285586c4bbdb'
down_revision: Union[str, Sequence[str], None] = 'efaf274996bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price_metrics', sa.Column('fifty_two_week_high_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('price_metrics', sa.Column('fifty_two_week_low_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('price_metrics', sa.Column('one_hundred_day_ema', sa.Float(), nullable=True))
    op.add_column('price_metrics', sa.Column('one_hundred_day_sma', sa.Float(), nullable=True))
    op.add_column('price_metrics', sa.Column('ten_day_average_trading_volume', sa.Float(), nullable=True))
    op.add_column('price_metrics', sa.Column('ten_day_ema', sa.Float(), nullable=True))
    op.add_column('price_metrics', sa.Column('ten_day_sma', sa.Float(), nullable=True))
    op.add_column('price_metrics', sa.Column('fifty_day_ema', sa.Float(), nullable=True))
    op.add_column('price_metrics', sa.Column('fifty_day_sma', sa.Float(), nullable=True))
    op.add_column('price_metrics', sa.Column('five_day_ema', sa.Float(), nullable=True))
    op.add_column('price_metrics', sa.Column('fourteen_day_rsi', sa.Float(), nullable=True))
    op.add_column('price_metrics', sa.Column('one_month_high', sa.Float(), nullable=True))
    op.add_column('price_metrics', sa.Column('one_month_high_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('price_metrics', sa.Column('ytd_price_return', sa.Float(), nullable=True))
    op.drop_column('price_metrics', 'current_price')
    op.drop_column('price_metrics', 'fifty_two_week_price_return_daily')
    op.drop_column('price_metrics', 'ytd_price_return_daily')
    op.drop_column('price_metrics', 'month_to_date_price_return_daily')
    op.drop_column('price_metrics', 'week_to_date_price_return_daily')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price_metrics', sa.Column('week_to_date_price_return_daily', mysql.FLOAT(), nullable=True))
    op.add_column('price_metrics', sa.Column('month_to_date_price_return_daily', mysql.FLOAT(), nullable=True))
    op.add_column('price_metrics', sa.Column('ytd_price_return_daily', mysql.FLOAT(), nullable=True))
    op.add_column('price_metrics', sa.Column('fifty_two_week_price_return_daily', mysql.FLOAT(), nullable=True))
    op.add_column('price_metrics', sa.Column('current_price', mysql.FLOAT(), nullable=True))
    op.drop_column('price_metrics', 'ytd_price_return')
    op.drop_column('price_metrics', 'one_month_high_date')
    op.drop_column('price_metrics', 'one_month_high')
    op.drop_column('price_metrics', 'fourteen_day_rsi')
    op.drop_column('price_metrics', 'five_day_ema')
    op.drop_column('price_metrics', 'fifty_day_sma')
    op.drop_column('price_metrics', 'fifty_day_ema')
    op.drop_column('price_metrics', 'ten_day_sma')
    op.drop_column('price_metrics', 'ten_day_ema')
    op.drop_column('price_metrics', 'ten_day_average_trading_volume')
    op.drop_column('price_metrics', 'one_hundred_day_sma')
    op.drop_column('price_metrics', 'one_hundred_day_ema')
    op.drop_column('price_metrics', 'fifty_two_week_low_date')
    op.drop_column('price_metrics', 'fifty_two_week_high_date')
    # ### end Alembic commands ###
