"""description

Revision ID: 350e20a82687
Revises: 5b75b43d7f87
Create Date: 2025-11-13 06:19:53.243822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '350e20a82687'
down_revision: Union[str, Sequence[str], None] = '5b75b43d7f87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('press_releases', sa.Column('datetime', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('press_releases', sa.Column('headline', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('press_releases', sa.Column('description', sa.Text(), nullable=True))
    op.drop_index(op.f('ix_press_releases_symbol'), table_name='press_releases')
    op.drop_column('press_releases', 'title')
    op.drop_column('press_releases', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('press_releases', sa.Column('date', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('press_releases', sa.Column('title', mysql.VARCHAR(length=255), nullable=False))
    op.create_index(op.f('ix_press_releases_symbol'), 'press_releases', ['symbol'], unique=False)
    op.drop_column('press_releases', 'description')
    op.drop_column('press_releases', 'headline')
    op.drop_column('press_releases', 'datetime')
    # ### end Alembic commands ###
