"""Add currency and finnhub_industry to company_profiles

Revision ID: 3fa01e57427b
Revises: ed0595b5433b
Create Date: 2025-11-12 22:53:58.748474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3fa01e57427b'
down_revision: Union[str, Sequence[str], None] = 'ed0595b5433b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_profiles', sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('company_profiles', sa.Column('finnhub_industry', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_profiles', 'finnhub_industry')
    op.drop_column('company_profiles', 'currency')
    # ### end Alembic commands ###
