"""update news table

Revision ID: 5b75b43d7f87
Revises: 7d38129883dc
Create Date: 2025-11-13 06:03:25.391999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5b75b43d7f87'
down_revision: Union[str, Sequence[str], None] = '7d38129883dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('company_news', 'summary',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('ipo_calendar', 'price',
               existing_type=mysql.FLOAT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ipo_calendar', 'price',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('company_news', 'summary',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
