"""Add quarter and year to eps_estimates

Revision ID: 694a1787f339
Revises: cb6c17efb895
Create Date: 2025-11-12 22:24:17.630424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '694a1787f339'
down_revision: Union[str, Sequence[str], None] = 'cb6c17efb895'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eps_estimates', sa.Column('quarter', sa.Integer(), nullable=True))
    op.add_column('eps_estimates', sa.Column('year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eps_estimates', 'year')
    op.drop_column('eps_estimates', 'quarter')
    # ### end Alembic commands ###
