"""add quarter and year to revenue_estimates

Revision ID: 710daf900ae9
Revises: eb0d90759f0e
Create Date: 2025-11-12 20:54:30.559176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '710daf900ae9'
down_revision: Union[str, Sequence[str], None] = 'eb0d90759f0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('revenue_estimates', sa.Column('quarter', sa.Integer(), nullable=True))
    op.add_column('revenue_estimates', sa.Column('year', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_revenue_estimates_period'), 'revenue_estimates', ['period'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_revenue_estimates_period'), table_name='revenue_estimates')
    op.drop_column('revenue_estimates', 'year')
    op.drop_column('revenue_estimates', 'quarter')
    # ### end Alembic commands ###
