"""update all revenue and estimates

Revision ID: 7d38129883dc
Revises: 6f84283b1dd7
Create Date: 2025-11-13 04:55:24.746726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7d38129883dc'
down_revision: Union[str, Sequence[str], None] = '6f84283b1dd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ebit_estimates', sa.Column('freq', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ebitda_estimates', sa.Column('freq', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('eps_estimates', sa.Column('freq', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('revenue_estimates', sa.Column('freq', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('revenue_estimates', 'freq')
    op.drop_column('eps_estimates', 'freq')
    op.drop_column('ebitda_estimates', 'freq')
    op.drop_column('ebit_estimates', 'freq')
    # ### end Alembic commands ###
