"""Add quarter and year to ebitda_estimates

Revision ID: 98aecb1cc336
Revises: 694a1787f339
Create Date: 2025-11-12 22:42:41.285412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98aecb1cc336'
down_revision: Union[str, Sequence[str], None] = '694a1787f339'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ebitda_estimates', sa.Column('quarter', sa.Integer(), nullable=True))
    op.add_column('ebitda_estimates', sa.Column('year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ebitda_estimates', 'year')
    op.drop_column('ebitda_estimates', 'quarter')
    # ### end Alembic commands ###
