"""update market holiday

Revision ID: bf203a4d1944
Revises: ed333ea09156
Create Date: 2025-11-12 17:08:07.684598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'bf203a4d1944'
down_revision: Union[str, Sequence[str], None] = 'ed333ea09156'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_holidays', sa.Column('event_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('market_holidays', sa.Column('trading_hour', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('market_holidays', sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('market_holidays', 'holiday_name')
    op.drop_column('market_holidays', 'event')
    op.drop_column('market_holidays', 'hours')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_holidays', sa.Column('hours', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('market_holidays', sa.Column('event', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('market_holidays', sa.Column('holiday_name', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('market_holidays', 'timezone')
    op.drop_column('market_holidays', 'trading_hour')
    op.drop_column('market_holidays', 'event_name')
    # ### end Alembic commands ###
