"""update the param

Revision ID: eb0d90759f0e
Revises: bf203a4d1944
Create Date: 2025-11-12 17:26:12.597477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb0d90759f0e'
down_revision: Union[str, Sequence[str], None] = 'bf203a4d1944'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price_targets', sa.Column('number_analysts', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('price_targets', 'number_analysts')
    # ### end Alembic commands ###
