"""Update basic_financials table to match API

Revision ID: ef9001fb48f1
Revises: f50c9cabaeef
Create Date: 2025-11-13 00:13:55.713432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'ef9001fb48f1'
down_revision: Union[str, Sequence[str], None] = 'f50c9cabaeef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('basic_financials', sa.Column('fifty_two_week_low_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('basic_financials', sa.Column('fifty_two_week_price_return_daily', sa.Float(), nullable=True))
    op.drop_column('basic_financials', 'pe_ratio')
    op.drop_column('basic_financials', 'eps')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('basic_financials', sa.Column('eps', mysql.FLOAT(), nullable=True))
    op.add_column('basic_financials', sa.Column('pe_ratio', mysql.FLOAT(), nullable=True))
    op.drop_column('basic_financials', 'fifty_two_week_price_return_daily')
    op.drop_column('basic_financials', 'fifty_two_week_low_date')
    # ### end Alembic commands ###
