"""add financial report model

Revision ID: 262637c5a8d7
Revises: fe73d42f3a1c
Create Date: 2025-11-04 13:18:43.123980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '262637c5a8d7'
down_revision: Union[str, Sequence[str], None] = 'fe73d42f3a1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financialreport',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cik', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=False),
    sa.Column('form', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('filed_date', sa.DateTime(), nullable=False),
    sa.Column('accepted_date', sa.DateTime(), nullable=False),
    sa.Column('report_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financialreport_access_number'), 'financialreport', ['access_number'], unique=False)
    op.create_index(op.f('ix_financialreport_cik'), 'financialreport', ['cik'], unique=False)
    op.create_index(op.f('ix_financialreport_symbol'), 'financialreport', ['symbol'], unique=False)
    op.create_index(op.f('ix_financialreport_year'), 'financialreport', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_financialreport_year'), table_name='financialreport')
    op.drop_index(op.f('ix_financialreport_symbol'), table_name='financialreport')
    op.drop_index(op.f('ix_financialreport_cik'), table_name='financialreport')
    op.drop_index(op.f('ix_financialreport_access_number'), table_name='financialreport')
    op.drop_table('financialreport')
    # ### end Alembic commands ###
