"""Create fund_ownership table

Revision ID: 59a633bec8aa
Revises: 005a6a095f04
Create Date: 2025-11-13 10:09:08.074631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '59a633bec8aa'
down_revision: Union[str, Sequence[str], None] = '005a6a095f04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fund_ownership', 'change',
               existing_type=mysql.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_column('fund_ownership', 'value')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fund_ownership', sa.Column('value', mysql.FLOAT(), nullable=True))
    op.alter_column('fund_ownership', 'change',
               existing_type=sa.Integer(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    # ### end Alembic commands ###
