"""update init db

Revision ID: 5a1cf5c32864
Revises: 
Create Date: 2025-11-10 16:52:57.184491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5a1cf5c32864'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_financials',
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('statement_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('period', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('frequency', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('net_income', sa.Float(), nullable=True),
    sa.Column('total_assets', sa.Float(), nullable=True),
    sa.Column('total_liabilities', sa.Float(), nullable=True),
    sa.Column('cash_flow', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'statement_type', 'period', 'frequency')
    )
    op.create_index(op.f('ix_company_financials_symbol'), 'company_financials', ['symbol'], unique=False)
    op.create_table('company_news',
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('datetime', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('headline', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('image', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('related', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'datetime', 'id')
    )
    op.create_index(op.f('ix_company_news_symbol'), 'company_news', ['symbol'], unique=False)
    op.create_table('company_ownership',
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('change', sa.Float(), nullable=True),
    sa.Column('filing_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('portfolio_percent', sa.Float(), nullable=True),
    sa.Column('share', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'name')
    )
    op.create_index(op.f('ix_company_ownership_symbol'), 'company_ownership', ['symbol'], unique=False)
    op.create_table('company_peers',
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('peer_symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('symbol', 'peer_symbol')
    )
    op.create_index(op.f('ix_company_peers_symbol'), 'company_peers', ['symbol'], unique=False)
    op.create_table('company_profiles',
    sa.Column('ticker', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('zip', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('weburl', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('logo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('naics', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('naics_national_industry', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('naics_sector', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('naics_subsector', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('exchange', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ipo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('market_capitalization', sa.Float(), nullable=True),
    sa.Column('share_outstanding', sa.Float(), nullable=True),
    sa.Column('employee_total', sa.Integer(), nullable=True),
    sa.Column('ggroup', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('gind', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('gsector', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('gsubind', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cusip', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('isin', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('lei', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sedol', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('ticker')
    )
    op.create_table('company_profiles_v2',
    sa.Column('ticker', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('exchange', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ipo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('market_capitalization', sa.Float(), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('share_outstanding', sa.Float(), nullable=True),
    sa.Column('weburl', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('logo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('finnhub_industry', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('ticker')
    )
    op.create_table('dividends',
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('adjusted_amount', sa.Float(), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('declaration_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('payment_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('record_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'date')
    )
    op.create_index(op.f('ix_dividends_symbol'), 'dividends', ['symbol'], unique=False)
    op.create_table('fund_ownership',
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('change', sa.Float(), nullable=True),
    sa.Column('filing_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('portfolio_percent', sa.Float(), nullable=True),
    sa.Column('share', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'name')
    )
    op.create_index(op.f('ix_fund_ownership_symbol'), 'fund_ownership', ['symbol'], unique=False)
    op.create_table('historical_market_cap',
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'date')
    )
    op.create_index(op.f('ix_historical_market_cap_symbol'), 'historical_market_cap', ['symbol'], unique=False)
    op.create_table('institutional_ownership',
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cik', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('change', sa.Float(), nullable=True),
    sa.Column('filing_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('no_voting', sa.Integer(), nullable=True),
    sa.Column('portfolio_percent', sa.Float(), nullable=True),
    sa.Column('share', sa.Integer(), nullable=True),
    sa.Column('shared_voting', sa.Integer(), nullable=True),
    sa.Column('sole_voting', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'cik')
    )
    op.create_index(op.f('ix_institutional_ownership_symbol'), 'institutional_ownership', ['symbol'], unique=False)
    op.create_table('institutional_portfolios',
    sa.Column('cik', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('filing_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('change', sa.Float(), nullable=True),
    sa.Column('no_voting', sa.Integer(), nullable=True),
    sa.Column('share', sa.Integer(), nullable=True),
    sa.Column('shared_voting', sa.Integer(), nullable=True),
    sa.Column('sole_voting', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('cik', 'symbol', 'filing_date')
    )
    op.create_index(op.f('ix_institutional_portfolios_cik'), 'institutional_portfolios', ['cik'], unique=False)
    op.create_table('institutional_profiles',
    sa.Column('cik', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('manager', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('profile', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('website', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('cik')
    )
    op.create_table('ipo_calendar',
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('exchange', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('number_of_shares', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('total_shares_value', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'date')
    )
    op.create_table('press_releases',
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'date', 'title')
    )
    op.create_index(op.f('ix_press_releases_symbol'), 'press_releases', ['symbol'], unique=False)
    op.create_table('price_metrics',
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fifty_two_week_high', sa.Float(), nullable=True),
    sa.Column('fifty_two_week_low', sa.Float(), nullable=True),
    sa.Column('fifty_two_week_price_return_daily', sa.Float(), nullable=True),
    sa.Column('ytd_price_return_daily', sa.Float(), nullable=True),
    sa.Column('month_to_date_price_return_daily', sa.Float(), nullable=True),
    sa.Column('week_to_date_price_return_daily', sa.Float(), nullable=True),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_table('reported_financials',
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cik', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('access_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('quarter', sa.Integer(), nullable=True),
    sa.Column('form', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('start_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('end_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('filed_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('accepted_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'cik', 'access_number')
    )
    op.create_index(op.f('ix_reported_financials_symbol'), 'reported_financials', ['symbol'], unique=False)
    op.create_table('sector_metrics',
    sa.Column('sector', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('region', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pe_ratio', sa.Float(), nullable=True),
    sa.Column('pb_ratio', sa.Float(), nullable=True),
    sa.Column('dividend_yield', sa.Float(), nullable=True),
    sa.Column('roe', sa.Float(), nullable=True),
    sa.Column('roa', sa.Float(), nullable=True),
    sa.Column('debt_to_equity', sa.Float(), nullable=True),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('sector', 'region')
    )
    op.create_table('stocksymbol',
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('figi', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mic', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('symbol')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stocksymbol')
    op.drop_table('sector_metrics')
    op.drop_index(op.f('ix_reported_financials_symbol'), table_name='reported_financials')
    op.drop_table('reported_financials')
    op.drop_table('price_metrics')
    op.drop_index(op.f('ix_press_releases_symbol'), table_name='press_releases')
    op.drop_table('press_releases')
    op.drop_table('ipo_calendar')
    op.drop_table('institutional_profiles')
    op.drop_index(op.f('ix_institutional_portfolios_cik'), table_name='institutional_portfolios')
    op.drop_table('institutional_portfolios')
    op.drop_index(op.f('ix_institutional_ownership_symbol'), table_name='institutional_ownership')
    op.drop_table('institutional_ownership')
    op.drop_index(op.f('ix_historical_market_cap_symbol'), table_name='historical_market_cap')
    op.drop_table('historical_market_cap')
    op.drop_index(op.f('ix_fund_ownership_symbol'), table_name='fund_ownership')
    op.drop_table('fund_ownership')
    op.drop_index(op.f('ix_dividends_symbol'), table_name='dividends')
    op.drop_table('dividends')
    op.drop_table('company_profiles_v2')
    op.drop_table('company_profiles')
    op.drop_index(op.f('ix_company_peers_symbol'), table_name='company_peers')
    op.drop_table('company_peers')
    op.drop_index(op.f('ix_company_ownership_symbol'), table_name='company_ownership')
    op.drop_table('company_ownership')
    op.drop_index(op.f('ix_company_news_symbol'), table_name='company_news')
    op.drop_table('company_news')
    op.drop_index(op.f('ix_company_financials_symbol'), table_name='company_financials')
    op.drop_table('company_financials')
    # ### end Alembic commands ###
