"""add all finnhub data models

Revision ID: 815b169043a8
Revises: 262637c5a8d7
Create Date: 2025-11-06 00:41:28.137705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '815b169043a8'
down_revision: Union[str, Sequence[str], None] = '262637c5a8d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('basic_financials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('metric', sa.JSON(), nullable=True),
    sa.Column('series', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_basic_financials_symbol'), 'basic_financials', ['symbol'], unique=True)
    op.create_table('company_executives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('since', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('compensation', sa.Float(), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('sex', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_executives_symbol'), 'company_executives', ['symbol'], unique=False)
    op.create_table('company_news',
    sa.Column('db_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('datetime', sa.Integer(), nullable=False),
    sa.Column('headline', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('image', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('related', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('db_id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_company_news_datetime'), 'company_news', ['datetime'], unique=False)
    op.create_index(op.f('ix_company_news_symbol'), 'company_news', ['symbol'], unique=False)
    op.create_table('company_peers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('peer', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_peers_peer'), 'company_peers', ['peer'], unique=False)
    op.create_index(op.f('ix_company_peers_symbol'), 'company_peers', ['symbol'], unique=False)
    op.create_table('dividends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('date', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('adjustedAmount', sa.Float(), nullable=True),
    sa.Column('payDate', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('recordDate', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('declarationDate', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dividends_date'), 'dividends', ['date'], unique=False)
    op.create_index(op.f('ix_dividends_symbol'), 'dividends', ['symbol'], unique=False)
    op.create_table('earnings_calendar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('date', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('epsActual', sa.Float(), nullable=True),
    sa.Column('epsEstimate', sa.Float(), nullable=True),
    sa.Column('revenueActual', sa.Float(), nullable=True),
    sa.Column('revenueEstimate', sa.Float(), nullable=True),
    sa.Column('hour', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_earnings_calendar_date'), 'earnings_calendar', ['date'], unique=False)
    op.create_index(op.f('ix_earnings_calendar_symbol'), 'earnings_calendar', ['symbol'], unique=False)
    op.create_table('eps_estimates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('freq', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('period', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('epsAvg', sa.Float(), nullable=True),
    sa.Column('epsHigh', sa.Float(), nullable=True),
    sa.Column('epsLow', sa.Float(), nullable=True),
    sa.Column('numberAnalysts', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eps_estimates_period'), 'eps_estimates', ['period'], unique=False)
    op.create_index(op.f('ix_eps_estimates_symbol'), 'eps_estimates', ['symbol'], unique=False)
    op.create_table('financial_report_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('cik', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=True),
    sa.Column('form', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('startDate', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('endDate', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('filedDate', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('acceptedDate', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('accessNumber', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('report', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_report_data_cik'), 'financial_report_data', ['cik'], unique=False)
    op.create_index(op.f('ix_financial_report_data_quarter'), 'financial_report_data', ['quarter'], unique=False)
    op.create_index(op.f('ix_financial_report_data_symbol'), 'financial_report_data', ['symbol'], unique=False)
    op.create_index(op.f('ix_financial_report_data_year'), 'financial_report_data', ['year'], unique=False)
    op.create_table('financials_standardized',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('statement', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('freq', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('cik', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('quarter', sa.Integer(), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financials_standardized_symbol'), 'financials_standardized', ['symbol'], unique=False)
    op.create_index(op.f('ix_financials_standardized_year'), 'financials_standardized', ['year'], unique=False)
    op.create_table('fund_ownership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('reportDate', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('share', sa.Float(), nullable=True),
    sa.Column('change', sa.Float(), nullable=True),
    sa.Column('portfolioPercent', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fund_ownership_reportDate'), 'fund_ownership', ['reportDate'], unique=False)
    op.create_index(op.f('ix_fund_ownership_symbol'), 'fund_ownership', ['symbol'], unique=False)
    op.create_table('general_news',
    sa.Column('db_id', sa.Integer(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('datetime', sa.Integer(), nullable=False),
    sa.Column('headline', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('image', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('related', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('db_id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_general_news_category'), 'general_news', ['category'], unique=False)
    op.create_index(op.f('ix_general_news_datetime'), 'general_news', ['datetime'], unique=False)
    op.create_table('historical_earnings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('period', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('actual', sa.Float(), nullable=True),
    sa.Column('estimate', sa.Float(), nullable=True),
    sa.Column('surprise', sa.Float(), nullable=True),
    sa.Column('surprisePercent', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historical_earnings_period'), 'historical_earnings', ['period'], unique=False)
    op.create_index(op.f('ix_historical_earnings_symbol'), 'historical_earnings', ['symbol'], unique=False)
    op.create_table('insider_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('transactionDate', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('filingDate', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('share', sa.Float(), nullable=True),
    sa.Column('change', sa.Float(), nullable=True),
    sa.Column('transactionCode', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('transactionPrice', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insider_transactions_symbol'), 'insider_transactions', ['symbol'], unique=False)
    op.create_index(op.f('ix_insider_transactions_transactionDate'), 'insider_transactions', ['transactionDate'], unique=False)
    op.create_table('institutional_ownership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('cik', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('reportDate', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('filingDate', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('share', sa.Float(), nullable=True),
    sa.Column('change', sa.Float(), nullable=True),
    sa.Column('portfolioPercent', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_institutional_ownership_cik'), 'institutional_ownership', ['cik'], unique=False)
    op.create_index(op.f('ix_institutional_ownership_reportDate'), 'institutional_ownership', ['reportDate'], unique=False)
    op.create_index(op.f('ix_institutional_ownership_symbol'), 'institutional_ownership', ['symbol'], unique=False)
    op.create_table('institutional_portfolios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cik', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('reportDate', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('filingDate', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('cusip', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('share', sa.Float(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('change', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_institutional_portfolios_cik'), 'institutional_portfolios', ['cik'], unique=False)
    op.create_index(op.f('ix_institutional_portfolios_reportDate'), 'institutional_portfolios', ['reportDate'], unique=False)
    op.create_index(op.f('ix_institutional_portfolios_symbol'), 'institutional_portfolios', ['symbol'], unique=False)
    op.create_table('institutional_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cik', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('manager', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_institutional_profiles_cik'), 'institutional_profiles', ['cik'], unique=True)
    op.create_table('ipo_calendar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('date', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('exchange', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('numberOfShares', sa.Float(), nullable=True),
    sa.Column('totalSharesValue', sa.Float(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ipo_calendar_date'), 'ipo_calendar', ['date'], unique=False)
    op.create_index(op.f('ix_ipo_calendar_symbol'), 'ipo_calendar', ['symbol'], unique=False)
    op.create_table('market_holidays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exchange', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('atDate', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('tradingDate', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('eventName', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_holidays_atDate'), 'market_holidays', ['atDate'], unique=False)
    op.create_index(op.f('ix_market_holidays_exchange'), 'market_holidays', ['exchange'], unique=False)
    op.create_index(op.f('ix_market_holidays_year'), 'market_holidays', ['year'], unique=False)
    op.create_table('market_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exchange', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.Column('isOpen', sa.Boolean(), nullable=False),
    sa.Column('session', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('holiday', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_status_checked_at'), 'market_status', ['checked_at'], unique=False)
    op.create_index(op.f('ix_market_status_exchange'), 'market_status', ['exchange'], unique=False)
    op.create_table('order_book_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('side', sqlmodel.sql.sqltypes.AutoString(length=4), nullable=False),
    sa.Column('p', sa.Float(), nullable=False),
    sa.Column('v', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_book_entries_symbol'), 'order_book_entries', ['symbol'], unique=False)
    op.create_index(op.f('ix_order_book_entries_timestamp'), 'order_book_entries', ['timestamp'], unique=False)
    op.create_table('press_releases',
    sa.Column('db_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('datetime', sa.Integer(), nullable=False),
    sa.Column('headline', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('db_id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_press_releases_datetime'), 'press_releases', ['datetime'], unique=False)
    op.create_index(op.f('ix_press_releases_symbol'), 'press_releases', ['symbol'], unique=False)
    op.create_table('price_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('targetHigh', sa.Float(), nullable=True),
    sa.Column('targetLow', sa.Float(), nullable=True),
    sa.Column('targetMean', sa.Float(), nullable=True),
    sa.Column('targetMedian', sa.Float(), nullable=True),
    sa.Column('lastUpdated', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_targets_symbol'), 'price_targets', ['symbol'], unique=True)
    op.create_table('recommendation_trends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('period', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('strongBuy', sa.Integer(), nullable=True),
    sa.Column('buy', sa.Integer(), nullable=True),
    sa.Column('hold', sa.Integer(), nullable=True),
    sa.Column('sell', sa.Integer(), nullable=True),
    sa.Column('strongSell', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_trends_period'), 'recommendation_trends', ['period'], unique=False)
    op.create_index(op.f('ix_recommendation_trends_symbol'), 'recommendation_trends', ['symbol'], unique=False)
    op.create_table('revenue_estimates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('freq', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('period', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('revenueAvg', sa.Float(), nullable=True),
    sa.Column('revenueHigh', sa.Float(), nullable=True),
    sa.Column('revenueLow', sa.Float(), nullable=True),
    sa.Column('numberAnalysts', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revenue_estimates_period'), 'revenue_estimates', ['period'], unique=False)
    op.create_index(op.f('ix_revenue_estimates_symbol'), 'revenue_estimates', ['symbol'], unique=False)
    op.create_table('sec_filings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('accessNumber', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('cik', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('form', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('filedDate', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('acceptedDate', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('reportUrl', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('filingUrl', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('accessNumber')
    )
    op.create_index(op.f('ix_sec_filings_cik'), 'sec_filings', ['cik'], unique=False)
    op.create_index(op.f('ix_sec_filings_filedDate'), 'sec_filings', ['filedDate'], unique=False)
    op.create_index(op.f('ix_sec_filings_form'), 'sec_filings', ['form'], unique=False)
    op.create_index(op.f('ix_sec_filings_symbol'), 'sec_filings', ['symbol'], unique=False)
    op.create_table('sector_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('sector', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('date', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('performance1d', sa.Float(), nullable=True),
    sa.Column('performance5d', sa.Float(), nullable=True),
    sa.Column('performance1m', sa.Float(), nullable=True),
    sa.Column('performance3m', sa.Float(), nullable=True),
    sa.Column('performance6m', sa.Float(), nullable=True),
    sa.Column('performanceYtd', sa.Float(), nullable=True),
    sa.Column('performance1y', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sector_metrics_date'), 'sector_metrics', ['date'], unique=False)
    op.create_index(op.f('ix_sector_metrics_region'), 'sector_metrics', ['region'], unique=False)
    op.create_index(op.f('ix_sector_metrics_sector'), 'sector_metrics', ['sector'], unique=False)
    op.create_table('stock_candles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('resolution', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False),
    sa.Column('t', sa.Integer(), nullable=False),
    sa.Column('o', sa.Float(), nullable=False),
    sa.Column('h', sa.Float(), nullable=False),
    sa.Column('l', sa.Float(), nullable=False),
    sa.Column('c', sa.Float(), nullable=False),
    sa.Column('v', sa.Float(), nullable=True),
    sa.Column('s', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_candles_symbol'), 'stock_candles', ['symbol'], unique=False)
    op.create_index(op.f('ix_stock_candles_t'), 'stock_candles', ['t'], unique=False)
    op.create_table('stock_quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('c', sa.Float(), nullable=True),
    sa.Column('d', sa.Float(), nullable=True),
    sa.Column('dp', sa.Float(), nullable=True),
    sa.Column('h', sa.Float(), nullable=True),
    sa.Column('l', sa.Float(), nullable=True),
    sa.Column('o', sa.Float(), nullable=True),
    sa.Column('pc', sa.Float(), nullable=True),
    sa.Column('t', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_quotes_symbol'), 'stock_quotes', ['symbol'], unique=False)
    op.create_table('stock_splits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('date', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('fromFactor', sa.Float(), nullable=False),
    sa.Column('toFactor', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_splits_date'), 'stock_splits', ['date'], unique=False)
    op.create_index(op.f('ix_stock_splits_symbol'), 'stock_splits', ['symbol'], unique=False)
    op.create_table('stock_symbols',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('displaySymbol', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('figi', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('mic', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('exchange', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_symbols_exchange'), 'stock_symbols', ['exchange'], unique=False)
    op.create_index(op.f('ix_stock_symbols_symbol'), 'stock_symbols', ['symbol'], unique=True)
    op.create_table('upgrade_downgrades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('gradeTime', sa.Integer(), nullable=False),
    sa.Column('company', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('fromGrade', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('toGrade', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_upgrade_downgrades_gradeTime'), 'upgrade_downgrades', ['gradeTime'], unique=False)
    op.create_index(op.f('ix_upgrade_downgrades_symbol'), 'upgrade_downgrades', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_upgrade_downgrades_symbol'), table_name='upgrade_downgrades')
    op.drop_index(op.f('ix_upgrade_downgrades_gradeTime'), table_name='upgrade_downgrades')
    op.drop_table('upgrade_downgrades')
    op.drop_index(op.f('ix_stock_symbols_symbol'), table_name='stock_symbols')
    op.drop_index(op.f('ix_stock_symbols_exchange'), table_name='stock_symbols')
    op.drop_table('stock_symbols')
    op.drop_index(op.f('ix_stock_splits_symbol'), table_name='stock_splits')
    op.drop_index(op.f('ix_stock_splits_date'), table_name='stock_splits')
    op.drop_table('stock_splits')
    op.drop_index(op.f('ix_stock_quotes_symbol'), table_name='stock_quotes')
    op.drop_table('stock_quotes')
    op.drop_index(op.f('ix_stock_candles_t'), table_name='stock_candles')
    op.drop_index(op.f('ix_stock_candles_symbol'), table_name='stock_candles')
    op.drop_table('stock_candles')
    op.drop_index(op.f('ix_sector_metrics_sector'), table_name='sector_metrics')
    op.drop_index(op.f('ix_sector_metrics_region'), table_name='sector_metrics')
    op.drop_index(op.f('ix_sector_metrics_date'), table_name='sector_metrics')
    op.drop_table('sector_metrics')
    op.drop_index(op.f('ix_sec_filings_symbol'), table_name='sec_filings')
    op.drop_index(op.f('ix_sec_filings_form'), table_name='sec_filings')
    op.drop_index(op.f('ix_sec_filings_filedDate'), table_name='sec_filings')
    op.drop_index(op.f('ix_sec_filings_cik'), table_name='sec_filings')
    op.drop_table('sec_filings')
    op.drop_index(op.f('ix_revenue_estimates_symbol'), table_name='revenue_estimates')
    op.drop_index(op.f('ix_revenue_estimates_period'), table_name='revenue_estimates')
    op.drop_table('revenue_estimates')
    op.drop_index(op.f('ix_recommendation_trends_symbol'), table_name='recommendation_trends')
    op.drop_index(op.f('ix_recommendation_trends_period'), table_name='recommendation_trends')
    op.drop_table('recommendation_trends')
    op.drop_index(op.f('ix_price_targets_symbol'), table_name='price_targets')
    op.drop_table('price_targets')
    op.drop_index(op.f('ix_press_releases_symbol'), table_name='press_releases')
    op.drop_index(op.f('ix_press_releases_datetime'), table_name='press_releases')
    op.drop_table('press_releases')
    op.drop_index(op.f('ix_order_book_entries_timestamp'), table_name='order_book_entries')
    op.drop_index(op.f('ix_order_book_entries_symbol'), table_name='order_book_entries')
    op.drop_table('order_book_entries')
    op.drop_index(op.f('ix_market_status_exchange'), table_name='market_status')
    op.drop_index(op.f('ix_market_status_checked_at'), table_name='market_status')
    op.drop_table('market_status')
    op.drop_index(op.f('ix_market_holidays_year'), table_name='market_holidays')
    op.drop_index(op.f('ix_market_holidays_exchange'), table_name='market_holidays')
    op.drop_index(op.f('ix_market_holidays_atDate'), table_name='market_holidays')
    op.drop_table('market_holidays')
    op.drop_index(op.f('ix_ipo_calendar_symbol'), table_name='ipo_calendar')
    op.drop_index(op.f('ix_ipo_calendar_date'), table_name='ipo_calendar')
    op.drop_table('ipo_calendar')
    op.drop_index(op.f('ix_institutional_profiles_cik'), table_name='institutional_profiles')
    op.drop_table('institutional_profiles')
    op.drop_index(op.f('ix_institutional_portfolios_symbol'), table_name='institutional_portfolios')
    op.drop_index(op.f('ix_institutional_portfolios_reportDate'), table_name='institutional_portfolios')
    op.drop_index(op.f('ix_institutional_portfolios_cik'), table_name='institutional_portfolios')
    op.drop_table('institutional_portfolios')
    op.drop_index(op.f('ix_institutional_ownership_symbol'), table_name='institutional_ownership')
    op.drop_index(op.f('ix_institutional_ownership_reportDate'), table_name='institutional_ownership')
    op.drop_index(op.f('ix_institutional_ownership_cik'), table_name='institutional_ownership')
    op.drop_table('institutional_ownership')
    op.drop_index(op.f('ix_insider_transactions_transactionDate'), table_name='insider_transactions')
    op.drop_index(op.f('ix_insider_transactions_symbol'), table_name='insider_transactions')
    op.drop_table('insider_transactions')
    op.drop_index(op.f('ix_historical_earnings_symbol'), table_name='historical_earnings')
    op.drop_index(op.f('ix_historical_earnings_period'), table_name='historical_earnings')
    op.drop_table('historical_earnings')
    op.drop_index(op.f('ix_general_news_datetime'), table_name='general_news')
    op.drop_index(op.f('ix_general_news_category'), table_name='general_news')
    op.drop_table('general_news')
    op.drop_index(op.f('ix_fund_ownership_symbol'), table_name='fund_ownership')
    op.drop_index(op.f('ix_fund_ownership_reportDate'), table_name='fund_ownership')
    op.drop_table('fund_ownership')
    op.drop_index(op.f('ix_financials_standardized_year'), table_name='financials_standardized')
    op.drop_index(op.f('ix_financials_standardized_symbol'), table_name='financials_standardized')
    op.drop_table('financials_standardized')
    op.drop_index(op.f('ix_financial_report_data_year'), table_name='financial_report_data')
    op.drop_index(op.f('ix_financial_report_data_symbol'), table_name='financial_report_data')
    op.drop_index(op.f('ix_financial_report_data_quarter'), table_name='financial_report_data')
    op.drop_index(op.f('ix_financial_report_data_cik'), table_name='financial_report_data')
    op.drop_table('financial_report_data')
    op.drop_index(op.f('ix_eps_estimates_symbol'), table_name='eps_estimates')
    op.drop_index(op.f('ix_eps_estimates_period'), table_name='eps_estimates')
    op.drop_table('eps_estimates')
    op.drop_index(op.f('ix_earnings_calendar_symbol'), table_name='earnings_calendar')
    op.drop_index(op.f('ix_earnings_calendar_date'), table_name='earnings_calendar')
    op.drop_table('earnings_calendar')
    op.drop_index(op.f('ix_dividends_symbol'), table_name='dividends')
    op.drop_index(op.f('ix_dividends_date'), table_name='dividends')
    op.drop_table('dividends')
    op.drop_index(op.f('ix_company_peers_symbol'), table_name='company_peers')
    op.drop_index(op.f('ix_company_peers_peer'), table_name='company_peers')
    op.drop_table('company_peers')
    op.drop_index(op.f('ix_company_news_symbol'), table_name='company_news')
    op.drop_index(op.f('ix_company_news_datetime'), table_name='company_news')
    op.drop_table('company_news')
    op.drop_index(op.f('ix_company_executives_symbol'), table_name='company_executives')
    op.drop_table('company_executives')
    op.drop_index(op.f('ix_basic_financials_symbol'), table_name='basic_financials')
    op.drop_table('basic_financials')
    # ### end Alembic commands ###
