"""update nullable in freq on estimates

Revision ID: 945311b1b799
Revises: f3dde39f1688
Create Date: 2025-11-08 02:18:15.700957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '945311b1b799'
down_revision: Union[str, Sequence[str], None] = 'f3dde39f1688'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('eps_estimates', 'freq',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('revenue_estimates', 'freq',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('revenue_estimates', 'freq',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('eps_estimates', 'freq',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    # ### end Alembic commands ###
