"""add matched_stocks table

Revision ID: c6a7a82f46e4
Revises: 5a1cf5c32864
Create Date: 2025-11-11 09:14:18.004122

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6a7a82f46e4'
down_revision: Union[str, Sequence[str], None] = '5a1cf5c32864'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matched_stocks',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('isin', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('exchange', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sub_industry', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ticker', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_price', sa.Float(), nullable=True),
    sa.Column('change', sa.Float(), nullable=True),
    sa.Column('changePercent', sa.Float(), nullable=True),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('exchange_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('indicator', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('type_stock', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_action_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('exchange_currency_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('min_order_size', sa.Float(), nullable=True),
    sa.Column('is_deleted', sa.Integer(), nullable=True),
    sa.Column('displaySymbol', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('finnhubCurrency', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('finnhubDescription', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('finnhubSymbol', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('finnhubType', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('finnhubMic', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('finnhubSheet', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('matchedBy', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matched_stocks_exchange'), 'matched_stocks', ['exchange'], unique=False)
    op.create_index(op.f('ix_matched_stocks_finnhubSymbol'), 'matched_stocks', ['finnhubSymbol'], unique=False)
    op.create_index(op.f('ix_matched_stocks_isin'), 'matched_stocks', ['isin'], unique=False)
    op.create_index(op.f('ix_matched_stocks_symbol'), 'matched_stocks', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matched_stocks_symbol'), table_name='matched_stocks')
    op.drop_index(op.f('ix_matched_stocks_isin'), table_name='matched_stocks')
    op.drop_index(op.f('ix_matched_stocks_finnhubSymbol'), table_name='matched_stocks')
    op.drop_index(op.f('ix_matched_stocks_exchange'), table_name='matched_stocks')
    op.drop_table('matched_stocks')
    # ### end Alembic commands ###
