"""Add quarter and year to revenue_estimates

Revision ID: cb6c17efb895
Revises: 710daf900ae9
Create Date: 2025-11-12 21:11:13.138062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb6c17efb895'
down_revision: Union[str, Sequence[str], None] = '710daf900ae9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_revenue_estimates_period'), table_name='revenue_estimates')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_revenue_estimates_period'), 'revenue_estimates', ['period'], unique=False)
    # ### end Alembic commands ###
