"""update chandle stick

Revision ID: d9d276fe3796
Revises: 0fb54e4bb57a
Create Date: 2025-11-13 16:42:33.660721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlmodel
# revision identifiers, used by Alembic.
revision: str = 'd9d276fe3796'
down_revision: Union[str, Sequence[str], None] = '0fb54e4bb57a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('institutional_portfolios', sa.Column('institution_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('institutional_portfolios', sa.Column('report_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('institutional_portfolios', sa.Column('percentage', sa.Float(), nullable=True))
    op.add_column('institutional_portfolios', sa.Column('put_call', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('institutional_portfolios', 'change',
               existing_type=mysql.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_index(op.f('ix_institutional_portfolios_cik'), table_name='institutional_portfolios')
    op.drop_column('institutional_portfolios', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('institutional_portfolios', sa.Column('name', mysql.VARCHAR(length=255), nullable=False))
    op.create_index(op.f('ix_institutional_portfolios_cik'), 'institutional_portfolios', ['cik'], unique=False)
    op.alter_column('institutional_portfolios', 'change',
               existing_type=sa.Integer(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.drop_column('institutional_portfolios', 'put_call')
    op.drop_column('institutional_portfolios', 'percentage')
    op.drop_column('institutional_portfolios', 'report_date')
    op.drop_column('institutional_portfolios', 'institution_name')
    
    # ### end Alembic commands ###
