"""Create company_profiles_v2 and company profile table

Revision ID: e3c898cbe3f2
Revises: 3fa01e57427b
Create Date: 2025-11-12 23:12:55.389943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3c898cbe3f2'
down_revision: Union[str, Sequence[str], None] = '3fa01e57427b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
