"""change insider transactions id to string

Revision ID: e4ce57245bd8
Revises: dcb23661063e
Create Date: 2025-11-08 02:05:31.352989

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e4ce57245bd8'
down_revision: Union[str, Sequence[str], None] = 'dcb23661063e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('insider_transactions', 'id',
               existing_type=mysql.INTEGER(),
               type_=sqlmodel.sql.sqltypes.AutoString(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('insider_transactions', 'id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=50),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
