"""Add quarter and year to ebit_estimates

Revision ID: ed0595b5433b
Revises: 98aecb1cc336
Create Date: 2025-11-12 22:47:27.024882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed0595b5433b'
down_revision: Union[str, Sequence[str], None] = '98aecb1cc336'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ebit_estimates', sa.Column('quarter', sa.Integer(), nullable=True))
    op.add_column('ebit_estimates', sa.Column('year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ebit_estimates', 'year')
    op.drop_column('ebit_estimates', 'quarter')
    # ### end Alembic commands ###
