"""update whole dbs base layout

Revision ID: ed333ea09156
Revises: 
Create Date: 2025-11-12 16:54:12.730381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ed333ea09156'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('basic_financials',
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('metric_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ten_day_avg_trading_volume', sa.Float(), nullable=True),
    sa.Column('fifty_two_week_high', sa.Float(), nullable=True),
    sa.Column('fifty_two_week_low', sa.Float(), nullable=True),
    sa.Column('beta', sa.Float(), nullable=True),
    sa.Column('market_capitalization', sa.Float(), nullable=True),
    sa.Column('pe_ratio', sa.Float(), nullable=True),
    sa.Column('eps', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'metric_type')
    )
    op.create_table('candlestick_data',
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'timestamp')
    )
    op.create_index(op.f('ix_candlestick_data_symbol'), 'candlestick_data', ['symbol'], unique=False)
    op.create_table('company_executives',
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('since', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sex', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('compensation', sa.Float(), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'name')
    )
    op.create_index(op.f('ix_company_executives_symbol'), 'company_executives', ['symbol'], unique=False)
    op.create_table('company_filings',
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('access_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cik', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('form', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('filed_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('accepted_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('report_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('filing_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'access_number')
    )
    op.create_index(op.f('ix_company_filings_symbol'), 'company_filings', ['symbol'], unique=False)
    op.create_table('company_financials',
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('statement_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('period', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('frequency', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('net_income', sa.Float(), nullable=True),
    sa.Column('total_assets', sa.Float(), nullable=True),
    sa.Column('total_liabilities', sa.Float(), nullable=True),
    sa.Column('cash_flow', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'statement_type', 'period', 'frequency')
    )
    op.create_index(op.f('ix_company_financials_symbol'), 'company_financials', ['symbol'], unique=False)
    op.create_table('company_news',
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('datetime', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('headline', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('image', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('related', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'datetime', 'id')
    )
    op.create_index(op.f('ix_company_news_symbol'), 'company_news', ['symbol'], unique=False)
    op.create_table('company_ownership',
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('change', sa.Float(), nullable=True),
    sa.Column('filing_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('share', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'name')
    )
    op.create_index(op.f('ix_company_ownership_symbol'), 'company_ownership', ['symbol'], unique=False)
    op.create_table('company_peers',
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('peers', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_index(op.f('ix_company_peers_symbol'), 'company_peers', ['symbol'], unique=False)
    op.create_table('company_profiles',
    sa.Column('ticker', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('zip', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('weburl', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('logo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('naics', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('naics_national_industry', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('naics_sector', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('naics_subsector', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('exchange', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ipo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('market_capitalization', sa.Float(), nullable=True),
    sa.Column('share_outstanding', sa.Float(), nullable=True),
    sa.Column('employee_total', sa.Integer(), nullable=True),
    sa.Column('ggroup', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('gind', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('gsector', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('gsubind', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cusip', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('isin', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('lei', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sedol', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('ticker')
    )
    op.create_table('company_profiles_v2',
    sa.Column('ticker', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('exchange', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ipo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('market_capitalization', sa.Float(), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('share_outstanding', sa.Float(), nullable=True),
    sa.Column('weburl', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('logo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('finnhub_industry', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('ticker')
    )
    op.create_table('dividends',
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('adjusted_amount', sa.Float(), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('declaration_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('payment_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('record_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'date')
    )
    op.create_index(op.f('ix_dividends_symbol'), 'dividends', ['symbol'], unique=False)
    op.create_table('earnings_calendar',
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('eps_actual', sa.Float(), nullable=True),
    sa.Column('eps_estimate', sa.Float(), nullable=True),
    sa.Column('hour', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('quarter', sa.Integer(), nullable=True),
    sa.Column('revenue_actual', sa.Float(), nullable=True),
    sa.Column('revenue_estimate', sa.Float(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'date')
    )
    op.create_index(op.f('ix_earnings_calendar_symbol'), 'earnings_calendar', ['symbol'], unique=False)
    op.create_table('earnings_data',
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('period', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('actual', sa.Float(), nullable=True),
    sa.Column('estimate', sa.Float(), nullable=True),
    sa.Column('surprise', sa.Float(), nullable=True),
    sa.Column('surprise_percent', sa.Float(), nullable=True),
    sa.Column('quarter', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'period')
    )
    op.create_index(op.f('ix_earnings_data_symbol'), 'earnings_data', ['symbol'], unique=False)
    op.create_table('earnings_quality_scores',
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('period', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('freq', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'period')
    )
    op.create_index(op.f('ix_earnings_quality_scores_symbol'), 'earnings_quality_scores', ['symbol'], unique=False)
    op.create_table('ebit_estimates',
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('period', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ebit_avg', sa.Float(), nullable=True),
    sa.Column('ebit_high', sa.Float(), nullable=True),
    sa.Column('ebit_low', sa.Float(), nullable=True),
    sa.Column('number_analysts', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'period')
    )
    op.create_index(op.f('ix_ebit_estimates_symbol'), 'ebit_estimates', ['symbol'], unique=False)
    op.create_table('ebitda_estimates',
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('period', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ebitda_avg', sa.Float(), nullable=True),
    sa.Column('ebitda_high', sa.Float(), nullable=True),
    sa.Column('ebitda_low', sa.Float(), nullable=True),
    sa.Column('number_analysts', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'period')
    )
    op.create_index(op.f('ix_ebitda_estimates_symbol'), 'ebitda_estimates', ['symbol'], unique=False)
    op.create_table('eps_estimates',
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('period', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('eps_avg', sa.Float(), nullable=True),
    sa.Column('eps_high', sa.Float(), nullable=True),
    sa.Column('eps_low', sa.Float(), nullable=True),
    sa.Column('number_analysts', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'period')
    )
    op.create_index(op.f('ix_eps_estimates_symbol'), 'eps_estimates', ['symbol'], unique=False)
    op.create_table('fund_ownership',
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('change', sa.Float(), nullable=True),
    sa.Column('filing_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('portfolio_percent', sa.Float(), nullable=True),
    sa.Column('share', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'name')
    )
    op.create_index(op.f('ix_fund_ownership_symbol'), 'fund_ownership', ['symbol'], unique=False)
    op.create_table('general_news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('datetime', sa.Integer(), nullable=True),
    sa.Column('headline', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('image', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('related', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historical_employee_count',
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('period_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('filing_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'period_date')
    )
    op.create_index(op.f('ix_historical_employee_count_symbol'), 'historical_employee_count', ['symbol'], unique=False)
    op.create_table('historical_market_cap',
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'date')
    )
    op.create_index(op.f('ix_historical_market_cap_symbol'), 'historical_market_cap', ['symbol'], unique=False)
    op.create_table('insider_transactions',
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('filing_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('transaction_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('share', sa.Float(), nullable=True),
    sa.Column('change', sa.Float(), nullable=True),
    sa.Column('transaction_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('transaction_price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'name', 'transaction_date')
    )
    op.create_index(op.f('ix_insider_transactions_symbol'), 'insider_transactions', ['symbol'], unique=False)
    op.create_table('institutional_ownership',
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cik', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('change', sa.Float(), nullable=True),
    sa.Column('filing_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('no_voting', sa.Integer(), nullable=True),
    sa.Column('portfolio_percent', sa.Float(), nullable=True),
    sa.Column('share', sa.Integer(), nullable=True),
    sa.Column('shared_voting', sa.Integer(), nullable=True),
    sa.Column('sole_voting', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'cik')
    )
    op.create_index(op.f('ix_institutional_ownership_symbol'), 'institutional_ownership', ['symbol'], unique=False)
    op.create_table('institutional_portfolios',
    sa.Column('cik', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('filing_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('change', sa.Float(), nullable=True),
    sa.Column('no_voting', sa.Integer(), nullable=True),
    sa.Column('share', sa.Integer(), nullable=True),
    sa.Column('shared_voting', sa.Integer(), nullable=True),
    sa.Column('sole_voting', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('cik', 'symbol', 'filing_date')
    )
    op.create_index(op.f('ix_institutional_portfolios_cik'), 'institutional_portfolios', ['cik'], unique=False)
    op.create_table('institutional_profiles',
    sa.Column('cik', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('manager', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('profile', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('website', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('cik')
    )
    op.create_table('ipo_calendar',
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('exchange', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('number_of_shares', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('total_shares_value', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'date')
    )
    op.create_table('market_holidays',
    sa.Column('exchange', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('holiday_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('event', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hours', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('exchange', 'date')
    )
    op.create_index(op.f('ix_market_holidays_exchange'), 'market_holidays', ['exchange'], unique=False)
    op.create_table('market_status',
    sa.Column('exchange', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_open', sa.Boolean(), nullable=True),
    sa.Column('session', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('holiday', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('exchange')
    )
    op.create_table('matched_stocks',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('isin', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('exchange', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sub_industry', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ticker', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_price', sa.Float(), nullable=True),
    sa.Column('change', sa.Float(), nullable=True),
    sa.Column('changePercent', sa.Float(), nullable=True),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('exchange_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('indicator', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('type_stock', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_action_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('exchange_currency_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('min_order_size', sa.Float(), nullable=True),
    sa.Column('is_deleted', sa.Integer(), nullable=True),
    sa.Column('displaySymbol', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('finnhubCurrency', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('finnhubDescription', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('finnhubSymbol', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('finnhubType', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('finnhubMic', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('finnhubSheet', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('matchedBy', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matched_stocks_exchange'), 'matched_stocks', ['exchange'], unique=False)
    op.create_index(op.f('ix_matched_stocks_finnhubSymbol'), 'matched_stocks', ['finnhubSymbol'], unique=False)
    op.create_index(op.f('ix_matched_stocks_isin'), 'matched_stocks', ['isin'], unique=False)
    op.create_index(op.f('ix_matched_stocks_symbol'), 'matched_stocks', ['symbol'], unique=False)
    op.create_table('press_releases',
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'date', 'title')
    )
    op.create_index(op.f('ix_press_releases_symbol'), 'press_releases', ['symbol'], unique=False)
    op.create_table('price_metrics',
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fifty_two_week_high', sa.Float(), nullable=True),
    sa.Column('fifty_two_week_low', sa.Float(), nullable=True),
    sa.Column('fifty_two_week_price_return_daily', sa.Float(), nullable=True),
    sa.Column('ytd_price_return_daily', sa.Float(), nullable=True),
    sa.Column('month_to_date_price_return_daily', sa.Float(), nullable=True),
    sa.Column('week_to_date_price_return_daily', sa.Float(), nullable=True),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_table('price_targets',
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_updated', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_high', sa.Float(), nullable=True),
    sa.Column('target_low', sa.Float(), nullable=True),
    sa.Column('target_mean', sa.Float(), nullable=True),
    sa.Column('target_median', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'last_updated')
    )
    op.create_index(op.f('ix_price_targets_symbol'), 'price_targets', ['symbol'], unique=False)
    op.create_table('realtime_quotes',
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('change', sa.Float(), nullable=True),
    sa.Column('percent_change', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('open_price', sa.Float(), nullable=True),
    sa.Column('previous_close', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'timestamp')
    )
    op.create_table('recommendations_trends',
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('period', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('buy', sa.Integer(), nullable=True),
    sa.Column('hold', sa.Integer(), nullable=True),
    sa.Column('sell', sa.Integer(), nullable=True),
    sa.Column('strong_buy', sa.Integer(), nullable=True),
    sa.Column('strong_sell', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'period')
    )
    op.create_index(op.f('ix_recommendations_trends_symbol'), 'recommendations_trends', ['symbol'], unique=False)
    op.create_table('reported_financials',
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cik', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('access_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('quarter', sa.Integer(), nullable=True),
    sa.Column('form', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('start_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('end_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('filed_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('accepted_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'cik', 'access_number')
    )
    op.create_index(op.f('ix_reported_financials_symbol'), 'reported_financials', ['symbol'], unique=False)
    op.create_table('revenue_estimates',
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('period', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('revenue_avg', sa.Float(), nullable=True),
    sa.Column('revenue_high', sa.Float(), nullable=True),
    sa.Column('revenue_low', sa.Float(), nullable=True),
    sa.Column('number_analysts', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'period')
    )
    op.create_index(op.f('ix_revenue_estimates_symbol'), 'revenue_estimates', ['symbol'], unique=False)
    op.create_table('sector_metrics',
    sa.Column('sector', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('region', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pe_ratio', sa.Float(), nullable=True),
    sa.Column('pb_ratio', sa.Float(), nullable=True),
    sa.Column('dividend_yield', sa.Float(), nullable=True),
    sa.Column('roe', sa.Float(), nullable=True),
    sa.Column('roa', sa.Float(), nullable=True),
    sa.Column('debt_to_equity', sa.Float(), nullable=True),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('sector', 'region')
    )
    op.create_table('stock_splits',
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('from_factor', sa.Float(), nullable=True),
    sa.Column('to_factor', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'date')
    )
    op.create_index(op.f('ix_stock_splits_symbol'), 'stock_splits', ['symbol'], unique=False)
    op.create_table('stocksymbol',
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('figi', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mic', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_table('technical_indicators',
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.Column('indicator', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('signal', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'timestamp', 'indicator')
    )
    op.create_index(op.f('ix_technical_indicators_symbol'), 'technical_indicators', ['symbol'], unique=False)
    op.create_table('upgrade_downgrades',
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('grade_time', sa.Integer(), nullable=False),
    sa.Column('company', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('from_grade', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('to_grade', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'grade_time', 'company')
    )
    op.create_index(op.f('ix_upgrade_downgrades_symbol'), 'upgrade_downgrades', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_upgrade_downgrades_symbol'), table_name='upgrade_downgrades')
    op.drop_table('upgrade_downgrades')
    op.drop_index(op.f('ix_technical_indicators_symbol'), table_name='technical_indicators')
    op.drop_table('technical_indicators')
    op.drop_table('stocksymbol')
    op.drop_index(op.f('ix_stock_splits_symbol'), table_name='stock_splits')
    op.drop_table('stock_splits')
    op.drop_table('sector_metrics')
    op.drop_index(op.f('ix_revenue_estimates_symbol'), table_name='revenue_estimates')
    op.drop_table('revenue_estimates')
    op.drop_index(op.f('ix_reported_financials_symbol'), table_name='reported_financials')
    op.drop_table('reported_financials')
    op.drop_index(op.f('ix_recommendations_trends_symbol'), table_name='recommendations_trends')
    op.drop_table('recommendations_trends')
    op.drop_table('realtime_quotes')
    op.drop_index(op.f('ix_price_targets_symbol'), table_name='price_targets')
    op.drop_table('price_targets')
    op.drop_table('price_metrics')
    op.drop_index(op.f('ix_press_releases_symbol'), table_name='press_releases')
    op.drop_table('press_releases')
    op.drop_index(op.f('ix_matched_stocks_symbol'), table_name='matched_stocks')
    op.drop_index(op.f('ix_matched_stocks_isin'), table_name='matched_stocks')
    op.drop_index(op.f('ix_matched_stocks_finnhubSymbol'), table_name='matched_stocks')
    op.drop_index(op.f('ix_matched_stocks_exchange'), table_name='matched_stocks')
    op.drop_table('matched_stocks')
    op.drop_table('market_status')
    op.drop_index(op.f('ix_market_holidays_exchange'), table_name='market_holidays')
    op.drop_table('market_holidays')
    op.drop_table('ipo_calendar')
    op.drop_table('institutional_profiles')
    op.drop_index(op.f('ix_institutional_portfolios_cik'), table_name='institutional_portfolios')
    op.drop_table('institutional_portfolios')
    op.drop_index(op.f('ix_institutional_ownership_symbol'), table_name='institutional_ownership')
    op.drop_table('institutional_ownership')
    op.drop_index(op.f('ix_insider_transactions_symbol'), table_name='insider_transactions')
    op.drop_table('insider_transactions')
    op.drop_index(op.f('ix_historical_market_cap_symbol'), table_name='historical_market_cap')
    op.drop_table('historical_market_cap')
    op.drop_index(op.f('ix_historical_employee_count_symbol'), table_name='historical_employee_count')
    op.drop_table('historical_employee_count')
    op.drop_table('general_news')
    op.drop_index(op.f('ix_fund_ownership_symbol'), table_name='fund_ownership')
    op.drop_table('fund_ownership')
    op.drop_index(op.f('ix_eps_estimates_symbol'), table_name='eps_estimates')
    op.drop_table('eps_estimates')
    op.drop_index(op.f('ix_ebitda_estimates_symbol'), table_name='ebitda_estimates')
    op.drop_table('ebitda_estimates')
    op.drop_index(op.f('ix_ebit_estimates_symbol'), table_name='ebit_estimates')
    op.drop_table('ebit_estimates')
    op.drop_index(op.f('ix_earnings_quality_scores_symbol'), table_name='earnings_quality_scores')
    op.drop_table('earnings_quality_scores')
    op.drop_index(op.f('ix_earnings_data_symbol'), table_name='earnings_data')
    op.drop_table('earnings_data')
    op.drop_index(op.f('ix_earnings_calendar_symbol'), table_name='earnings_calendar')
    op.drop_table('earnings_calendar')
    op.drop_index(op.f('ix_dividends_symbol'), table_name='dividends')
    op.drop_table('dividends')
    op.drop_table('company_profiles_v2')
    op.drop_table('company_profiles')
    op.drop_index(op.f('ix_company_peers_symbol'), table_name='company_peers')
    op.drop_table('company_peers')
    op.drop_index(op.f('ix_company_ownership_symbol'), table_name='company_ownership')
    op.drop_table('company_ownership')
    op.drop_index(op.f('ix_company_news_symbol'), table_name='company_news')
    op.drop_table('company_news')
    op.drop_index(op.f('ix_company_financials_symbol'), table_name='company_financials')
    op.drop_table('company_financials')
    op.drop_index(op.f('ix_company_filings_symbol'), table_name='company_filings')
    op.drop_table('company_filings')
    op.drop_index(op.f('ix_company_executives_symbol'), table_name='company_executives')
    op.drop_table('company_executives')
    op.drop_index(op.f('ix_candlestick_data_symbol'), table_name='candlestick_data')
    op.drop_table('candlestick_data')
    op.drop_table('basic_financials')
    # ### end Alembic commands ###
