"""Create historical_employee_count table

Revision ID: efaf274996bd
Revises: f362fb61576a
Create Date: 2025-11-12 23:38:55.213553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'efaf274996bd'
down_revision: Union[str, Sequence[str], None] = 'f362fb61576a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('historical_employee_count', 'filing_date')
    op.drop_column('historical_employee_count', 'source')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('historical_employee_count', sa.Column('source', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('historical_employee_count', sa.Column('filing_date', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
