"""Create company_executives table

Revision ID: f362fb61576a
Revises: e3c898cbe3f2
Create Date: 2025-11-12 23:31:07.514204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'f362fb61576a'
down_revision: Union[str, Sequence[str], None] = 'e3c898cbe3f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_executives', sa.Column('position', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('company_executives', 'compensation',
               existing_type=mysql.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_column('company_executives', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_executives', sa.Column('title', mysql.VARCHAR(length=255), nullable=True))
    op.alter_column('company_executives', 'compensation',
               existing_type=sa.Integer(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.drop_column('company_executives', 'position')
    # ### end Alembic commands ###
