"""update nullable in estmates , ownership , peer tables

Revision ID: f3dde39f1688
Revises: e4ce57245bd8
Create Date: 2025-11-08 02:14:52.522444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f3dde39f1688'
down_revision: Union[str, Sequence[str], None] = 'e4ce57245bd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('company_news', 'summary',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('company_peers', 'peer',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('eps_estimates', 'symbol',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('general_news', 'summary',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('institutional_ownership', 'symbol',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('revenue_estimates', 'symbol',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('revenue_estimates', 'symbol',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('institutional_ownership', 'symbol',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('general_news', 'summary',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('eps_estimates', 'symbol',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('company_peers', 'peer',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('company_news', 'summary',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
