"""create user table

Revision ID: fe73d42f3a1c
Revises: 
Create Date: 2025-11-03 11:18:26.173894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'fe73d42f3a1c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companyprofile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cusip', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sedol', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('isin', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('employeeTotal', sa.Integer(), nullable=True),
    sa.Column('exchange', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ggroup', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('gind', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('gsector', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('gsubind', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ipo', sa.Date(), nullable=True),
    sa.Column('marketCapitalization', sa.Float(), nullable=True),
    sa.Column('naics', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('naicsNationalIndustry', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('naicsSector', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('naicsSubsector', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ticker', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('finnhubIndustry', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('weburl', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('logo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('shareOutstanding', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('companyprofile')
    # ### end Alembic commands ###
