"""Handler to Model mapping configurations for testing and ETL operations."""
from datetime import datetime, timedelta

from config.handlers import (
    get_stock_symbols,
    get_company_profile,
    get_company_profile2,
    get_company_peers,
    get_company_ownership,
    get_company_news,
    get_press_release,
    get_fund_ownership,
    get_institutional_profile,
    get_institutional_portfolio,
    get_institutional_ownership,
    get_company_basic_financials,
    get_company_financials,
    get_company_reported_financials,
    get_company_dividends,
    get_company_price_metrics,
    get_sector_metrics,
    get_ipo_calendar,
    get_historical_mcap,
)

from src.models import (
    StockSymbol,
    CompanyProfile,
    CompanyProfile2,
    CompanyPeer,
    CompanyOwnership,
    CompanyNews,
    PressRelease,
    FundOwnership,
    InstitutionalProfile,
    InstitutionalPortfolio,
    InstitutionalOwnership,
    BasicFinancials,
    CompanyFinancials,
    ReportedFinancials,
    Dividend,
    PriceMetrics,
    SectorMetrics,
    IpoCalendar,
    HistoricalMarketCap,
)


# Handler to Model Mapping Array
HANDLER_MODEL_TESTS = [
    {
        "handler": get_stock_symbols,
        "name": "Stock Symbols",
        "params": {"exchange": "US"},
        "model": StockSymbol,
        "data_key": None,  # Data is directly a list
        "limit": 10,  # Limit records to insert for testing
    },
    {
        "handler": get_company_profile,
        "name": "Company Profile (v1)",
        "params": {"symbol": "AAPL"},
        "model": CompanyProfile,
        "data_key": None,  # Data is a single dict
        "limit": None,
    },
    {
        "handler": get_company_profile2,
        "name": "Company Profile (v2)",
        "params": {"symbol": "AAPL"},
        "model": CompanyProfile2,
        "data_key": None,
        "limit": None,
    },
    {
        "handler": get_company_peers,
        "name": "Company Peers",
        "params": {"symbol": "AAPL"},
        "model": CompanyPeer,
        "data_key": None,  # Data is a list of strings
        "limit": None,
        "transform": lambda data, symbol: [{"symbol": symbol, "peer_symbol": peer} for peer in data],
    },
    {
        "handler": get_company_ownership,
        "name": "Company Ownership",
        "params": {
            "symbol": "AAPL",
            "from_date": "2020-01-01",
            "to_date": "2024-12-31",
        },
        "model": CompanyOwnership,
        "data_key": "ownership",
        "limit": 10,
    },
    {
        "handler": get_company_news,
        "name": "Company News",
        "params": {
            "symbol": "AAPL",
            "from_date": (datetime.now() - timedelta(days=7)).strftime("%Y-%m-%d"),
            "to_date": datetime.now().strftime("%Y-%m-%d"),
        },
        "model": CompanyNews,
        "data_key": None,
        "limit": 5,
        "transform": lambda data, symbol: [{**item, "symbol": symbol} for item in data],
    },
    {
        "handler": get_press_release,
        "name": "Press Releases",
        "params": {
            "symbol": "AAPL",
            "from_date": "2024-01-01",
            "to_date": "2024-12-31",
        },
        "model": PressRelease,
        "data_key": "majorDevelopment",
        "limit": 5,
        "transform": lambda data, symbol: [{**item, "symbol": symbol} for item in data],
    },
    {
        "handler": get_fund_ownership,
        "name": "Fund Ownership",
        "params": {
            "symbol": "AAPL",
            "from_date": "2020-01-01",
            "to_date": "2024-12-31",
        },
        "model": FundOwnership,
        "data_key": "ownership",
        "limit": 10,
    },
    {
        "handler": get_institutional_profile,
        "name": "Institutional Profile",
        "params": {},
        "model": InstitutionalProfile,
        "data_key": "data",
        "limit": 10,
    },
    {
        "handler": get_institutional_portfolio,
        "name": "Institutional Portfolio",
        "params": {
            "cik": "0001067983",
            "from_date": "2020-01-01",
            "to_date": "2024-12-31",
        },
        "model": InstitutionalPortfolio,
        "data_key": "data",
        "limit": 10,
    },
    {
        "handler": get_institutional_ownership,
        "name": "Institutional Ownership",
        "params": {
            "symbol": "AAPL",
            "from_date": "2020-01-01",
            "to_date": "2024-12-31",
        },
        "model": InstitutionalOwnership,
        "data_key": "ownership",
        "limit": 10,
    },
    {
        "handler": get_company_basic_financials,
        "name": "Company Basic Financials",
        "params": {"symbol": "AAPL", "metric": "all"},
        "model": BasicFinancials,
        "data_key": None,
        "limit": None,
        "transform": lambda data, symbol: {**data, "symbol": symbol} if isinstance(data, dict) else data,
    },
    {
        "handler": get_company_financials,
        "name": "Company Financials",
        "params": {"symbol": "AAPL", "statement": "income", "freq": "annual"},
        "model": CompanyFinancials,
        "data_key": "financials",
        "limit": 5,
        "transform": lambda data, symbol: [{**item, "symbol": symbol} for item in data],
    },
    {
        "handler": get_company_reported_financials,
        "name": "Company Reported Financials",
        "params": {"symbol": "AAPL"},
        "model": ReportedFinancials,
        "data_key": "data",
        "limit": 5,
        "transform": lambda data, symbol: [{**item, "symbol": symbol} for item in data],
    },
    {
        "handler": get_company_dividends,
        "name": "Company Dividends",
        "params": {
            "symbol": "AAPL",
            "from_date": "2020-01-01",
            "to_date": "2024-12-31",
        },
        "model": Dividend,
        "data_key": None,
        "limit": 10,
        "transform": lambda data, symbol: [{**item, "symbol": symbol} for item in data],
    },
    {
        "handler": get_company_price_metrics,
        "name": "Company Price Metrics",
        "params": {"symbol": "AAPL"},
        "model": PriceMetrics,
        "data_key": None,
        "limit": None,
        "transform": lambda data, symbol: {**data, "symbol": symbol} if isinstance(data, dict) else data,
    },
    {
        "handler": get_sector_metrics,
        "name": "Sector Metrics",
        "params": {"region": "US"},
        "model": SectorMetrics,
        "data_key": None,
        "limit": 10,
    },
    {
        "handler": get_ipo_calendar,
        "name": "IPO Calendar",
        "params": {
            "from_date": (datetime.now() - timedelta(days=30)).strftime("%Y-%m-%d"),
            "to_date": datetime.now().strftime("%Y-%m-%d"),
        },
        "model": IpoCalendar,
        "data_key": "ipoCalendar",
        "limit": 5,
    },
    {
        "handler": get_historical_mcap,
        "name": "Historical Market Cap",
        "params": {
            "symbol": "AAPL",
            "from_date": "2024-01-01",
            "to_date": "2024-12-31",
        },
        "model": HistoricalMarketCap,
        "data_key": None,
        "limit": 10,
        "transform": lambda data, symbol: [{**item, "symbol": symbol} for item in data],
    },
]


# Dictionary version for single handler testing
HANDLER_MODEL_DICT = {
    "stock_symbols": {
        "handler": get_stock_symbols,
        "name": "Stock Symbols",
        "params": {"exchange": "US"},
        "model": StockSymbol,
        "limit": 10,
    },
    "company_profile": {
        "handler": get_company_profile,
        "name": "Company Profile (v1)",
        "params": {"symbol": "AAPL"},
        "model": CompanyProfile,
    },
    "company_profile2": {
        "handler": get_company_profile2,
        "name": "Company Profile (v2)",
        "params": {"symbol": "AAPL"},
        "model": CompanyProfile2,
    },
    "company_peers": {
        "handler": get_company_peers,
        "name": "Company Peers",
        "params": {"symbol": "AAPL"},
        "model": CompanyPeer,
    },
    "company_ownership": {
        "handler": get_company_ownership,
        "name": "Company Ownership",
        "params": {
            "symbol": "AAPL",
            "from_date": "2020-01-01",
            "to_date": "2024-12-31",
        },
        "model": CompanyOwnership,
        "limit": 10,
    },
    "company_news": {
        "handler": get_company_news,
        "name": "Company News",
        "params": {
            "symbol": "AAPL",
            "from_date": (datetime.now() - timedelta(days=7)).strftime("%Y-%m-%d"),
            "to_date": datetime.now().strftime("%Y-%m-%d"),
        },
        "model": CompanyNews,
        "limit": 5,
    },
    "press_release": {
        "handler": get_press_release,
        "name": "Press Releases",
        "params": {
            "symbol": "AAPL",
            "from_date": "2024-01-01",
            "to_date": "2024-12-31",
        },
        "model": PressRelease,
        "limit": 5,
    },
    "fund_ownership": {
        "handler": get_fund_ownership,
        "name": "Fund Ownership",
        "params": {
            "symbol": "AAPL",
            "from_date": "2020-01-01",
            "to_date": "2024-12-31",
        },
        "model": FundOwnership,
        "limit": 10,
    },
    "institutional_profile": {
        "handler": get_institutional_profile,
        "name": "Institutional Profile",
        "params": {},
        "model": InstitutionalProfile,
        "limit": 10,
    },
    "institutional_portfolio": {
        "handler": get_institutional_portfolio,
        "name": "Institutional Portfolio",
        "params": {
            "cik": "0001067983",
            "from_date": "2020-01-01",
            "to_date": "2024-12-31",
        },
        "model": InstitutionalPortfolio,
        "limit": 10,
    },
    "institutional_ownership": {
        "handler": get_institutional_ownership,
        "name": "Institutional Ownership",
        "params": {
            "symbol": "AAPL",
            "from_date": "2020-01-01",
            "to_date": "2024-12-31",
        },
        "model": InstitutionalOwnership,
        "limit": 10,
    },
    "basic_financials": {
        "handler": get_company_basic_financials,
        "name": "Company Basic Financials",
        "params": {"symbol": "AAPL", "metric": "all"},
        "model": BasicFinancials,
    },
    "company_financials": {
        "handler": get_company_financials,
        "name": "Company Financials",
        "params": {"symbol": "AAPL", "statement": "income", "freq": "annual"},
        "model": CompanyFinancials,
        "limit": 5,
    },
    "reported_financials": {
        "handler": get_company_reported_financials,
        "name": "Company Reported Financials",
        "params": {"symbol": "AAPL"},
        "model": ReportedFinancials,
        "limit": 5,
    },
    "dividends": {
        "handler": get_company_dividends,
        "name": "Company Dividends",
        "params": {
            "symbol": "AAPL",
            "from_date": "2020-01-01",
            "to_date": "2024-12-31",
        },
        "model": Dividend,
        "limit": 10,
    },
    "price_metrics": {
        "handler": get_company_price_metrics,
        "name": "Company Price Metrics",
        "params": {"symbol": "AAPL"},
        "model": PriceMetrics,
    },
    "sector_metrics": {
        "handler": get_sector_metrics,
        "name": "Sector Metrics",
        "params": {"region": "US"},
        "model": SectorMetrics,
        "limit": 10,
    },
    "ipo_calendar": {
        "handler": get_ipo_calendar,
        "name": "IPO Calendar",
        "params": {
            "from_date": (datetime.now() - timedelta(days=30)).strftime("%Y-%m-%d"),
            "to_date": datetime.now().strftime("%Y-%m-%d"),
        },
        "model": IpoCalendar,
        "limit": 5,
    },
    "historical_mcap": {
        "handler": get_historical_mcap,
        "name": "Historical Market Cap",
        "params": {
            "symbol": "AAPL",
            "from_date": "2024-01-01",
            "to_date": "2024-12-31",
        },
        "model": HistoricalMarketCap,
        "limit": 10,
    },
}
